#include "fancy_ui/steppenface/ui_assets.hpp"

#include <array>

namespace fancy_ui::steppenface {

std::span<const UiFontAssetSpec> RequiredUiFontAssets() {
  static constexpr std::array kFonts{
      UiFontAssetSpec{"NotoSans-Thin.ttf", UiFontWeight::Thin},
      UiFontAssetSpec{"NotoSans-ExtraLight.ttf", UiFontWeight::ExtraLight},
      UiFontAssetSpec{"NotoSans-Light.ttf", UiFontWeight::Light},
      UiFontAssetSpec{"NotoSans-Regular.ttf", UiFontWeight::Regular},
      UiFontAssetSpec{"NotoSans-Medium.ttf", UiFontWeight::Medium},
      UiFontAssetSpec{"NotoSans-SemiBold.ttf", UiFontWeight::SemiBold},
      UiFontAssetSpec{"NotoSans-Bold.ttf", UiFontWeight::Bold},
      UiFontAssetSpec{"NotoSans-ExtraBold.ttf", UiFontWeight::ExtraBold},
      UiFontAssetSpec{"NotoSans-Black.ttf", UiFontWeight::Black},
      UiFontAssetSpec{"NotoSansMono-Regular.ttf", UiFontWeight::Regular, true},
  };
  return kFonts;
}

std::span<const UiIconAssetSpec> UiIconAssets() {
  static constexpr std::array kIcons{
      UiIconAssetSpec{"alert", UiIconSize::Small16, "alert-16.svg"},
      UiIconAssetSpec{"send", UiIconSize::Small16, "arrow-right-16.svg"},
      UiIconAssetSpec{"view", UiIconSize::Small16, "camera-16.svg"},
      UiIconAssetSpec{"check", UiIconSize::Small16, "check-16.svg"},
      UiIconAssetSpec{"machines", UiIconSize::Small16, "cpu-16.svg"},
      UiIconAssetSpec{"chevron-down", UiIconSize::Small16,
                      "chevron-down-16.svg"},
      UiIconAssetSpec{"visibility", UiIconSize::Small16, "eye-16.svg"},
      UiIconAssetSpec{"visibility-off", UiIconSize::Small16,
                      "eye-closed-16.svg"},
      UiIconAssetSpec{"fit", UiIconSize::Small16, "fit-all-16.svg"},
      UiIconAssetSpec{"focus", UiIconSize::Small16, "focus-selected-16.svg"},
      UiIconAssetSpec{"settings", UiIconSize::Small16, "gear-16.svg"},
      UiIconAssetSpec{"information", UiIconSize::Small16, "info-16.svg"},
      UiIconAssetSpec{"license", UiIconSize::Small16, "key-16.svg"},
      UiIconAssetSpec{"legal", UiIconSize::Small16, "law-16.svg"},
      UiIconAssetSpec{"layout-explorer-closed", UiIconSize::Small16,
                      "layout-left-closed-16.svg"},
      UiIconAssetSpec{"layout-explorer-open", UiIconSize::Small16,
                      "layout-left-open-16.svg"},
      UiIconAssetSpec{"layout-operation-closed", UiIconSize::Small16,
                      "layout-bottom-closed-16.svg"},
      UiIconAssetSpec{"layout-operation-open", UiIconSize::Small16,
                      "layout-bottom-open-16.svg"},
      UiIconAssetSpec{"layout-inspector-closed", UiIconSize::Small16,
                      "layout-right-closed-16.svg"},
      UiIconAssetSpec{"layout-inspector-open", UiIconSize::Small16,
                      "layout-right-open-16.svg"},
      UiIconAssetSpec{"orbit-locked", UiIconSize::Small16, "lock-16.svg"},
      UiIconAssetSpec{"more", UiIconSize::Small16, "kebab-horizontal-16.svg"},
      UiIconAssetSpec{"plus", UiIconSize::Small16, "plus-16.svg"},
      UiIconAssetSpec{"appearance", UiIconSize::Small16, "paintbrush-16.svg"},
      UiIconAssetSpec{"busy", UiIconSize::Small16, "sync-16.svg"},
      UiIconAssetSpec{"success", UiIconSize::Small16, "check-circle-16.svg"},
      UiIconAssetSpec{"triangle-down", UiIconSize::Small16,
                      "triangle-down-16.svg"},
      UiIconAssetSpec{"failure", UiIconSize::Small16, "x-circle-16.svg"},
      UiIconAssetSpec{"orbit-unlocked", UiIconSize::Small16, "unlock-16.svg"},
      UiIconAssetSpec{"file", UiIconSize::Small16, "file-16.svg"},
      UiIconAssetSpec{"folder", UiIconSize::Small16, "folder-16.svg"},
      UiIconAssetSpec{"typography", UiIconSize::Small16, "typography-16.svg"},
      UiIconAssetSpec{"model", UiIconSize::Small16, "package-16.svg"},
      UiIconAssetSpec{"model", UiIconSize::Rail24, "package-24.svg"},
      UiIconAssetSpec{"bed", UiIconSize::Small16, "bed-16.svg"},
      UiIconAssetSpec{"bed", UiIconSize::Rail24, "bed-24.svg"},
      UiIconAssetSpec{"svg", UiIconSize::Small16, "svg-data-16.svg"},
      UiIconAssetSpec{"svg", UiIconSize::Rail24, "svg-data-24.svg"},
      UiIconAssetSpec{"dxf", UiIconSize::Small16, "dxf-data-16.svg"},
      UiIconAssetSpec{"dxf", UiIconSize::Rail24, "dxf-data-24.svg"},
      UiIconAssetSpec{"path", UiIconSize::Small16, "path-data-16.svg"},
      UiIconAssetSpec{"path", UiIconSize::Rail24, "path-data-24.svg"},
      UiIconAssetSpec{"line", UiIconSize::Small16, "line-16.svg"},
      UiIconAssetSpec{"line", UiIconSize::Rail24, "line-24.svg"},
      UiIconAssetSpec{"arc", UiIconSize::Small16, "arc-16.svg"},
      UiIconAssetSpec{"arc", UiIconSize::Rail24, "arc-24.svg"},
      UiIconAssetSpec{"circle", UiIconSize::Small16, "circle-16.svg"},
      UiIconAssetSpec{"circle", UiIconSize::Rail24, "circle-24.svg"},
      UiIconAssetSpec{"select-children", UiIconSize::Small16,
                      "select-children-16.svg"},
      UiIconAssetSpec{"select-children", UiIconSize::Rail24,
                      "select-children-24.svg"},
      UiIconAssetSpec{"objects", UiIconSize::Small16, "stack-16.svg"},
      UiIconAssetSpec{"objects", UiIconSize::Rail24, "stack-24.svg"},
      UiIconAssetSpec{"grain", UiIconSize::Small16, "grain-direction-16.svg"},
      UiIconAssetSpec{"grain", UiIconSize::Rail24, "grain-direction-24.svg"},
      UiIconAssetSpec{"search", UiIconSize::Small16, "search-16.svg"},
      UiIconAssetSpec{"search", UiIconSize::Rail24, "search-24.svg"},
      UiIconAssetSpec{"compact", UiIconSize::Small16, "compact-16.svg"},
      UiIconAssetSpec{"compact", UiIconSize::Rail24, "compact-24.svg"},
      UiIconAssetSpec{"diagnostics", UiIconSize::Small16, "pulse-16.svg"},
      UiIconAssetSpec{"diagnostics", UiIconSize::Rail24, "pulse-24.svg"},
      UiIconAssetSpec{"settings", UiIconSize::Rail24, "gear-24.svg"},
  };
  return kIcons;
}

} // namespace fancy_ui::steppenface
